# Generated by Django 2.2.5 on 2019-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doc',
            field=models.FileField(null=True, upload_to='file\\'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(null=True, upload_to='image\\'),
        ),
    ]
