# Generated by Django 2.2.5 on 2019-11-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_auto_20191127_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.AddField(
            model_name='notice',
            name='img',
            field=models.ImageField(null=True, upload_to='image\\'),
        ),
    ]
