# Generated by Django 2.2.5 on 2019-11-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_auto_20191129_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Notice'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=12)),
                ('phonee', models.CharField(max_length=12)),
                ('cr_datee', models.DateTimeField(auto_now_add=True)),
                ('msgg', models.TextField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Profile')),
            ],
        ),
    ]
