# Generated by Django 2.2.5 on 2019-11-30 04:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitalapp', '0010_auto_20191130_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='cr_datee',
            new_name='cr_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='msgg',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='hod',
            new_name='dep',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='namee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phonee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='pn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
