# Generated by Django 2.2.5 on 2019-11-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0011_auto_20191130_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='depertment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
