# Generated by Django 2.2.5 on 2019-11-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0013_auto_20191130_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
