# Generated by Django 2.2.5 on 2019-11-30 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0014_auto_20191130_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')]),
        ),
    ]
