# Generated by Django 2.2.5 on 2019-11-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0015_auto_20191130_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pn',
        ),
    ]
