# Generated by Django 2.2.5 on 2019-12-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0017_auto_20191130_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='image\\')),
                ('name', models.CharField(max_length=100)),
                ('dep', models.CharField(max_length=100)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
