# Generated by Django 2.2.5 on 2019-12-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0018_auto_20191202_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='dep',
            new_name='depertment',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='msg',
            new_name='description',
        ),
    ]
