# Generated by Django 2.2.5 on 2019-12-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0019_auto_20191202_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='img',
            new_name='picture',
        ),
    ]
